// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeBPMKey(arg1) {
  return window['go']['main']['App']['AnalyzeBPMKey'](arg1);
}

export function AnalyzeLoudness(arg1) {
  return window['go']['main']['App']['AnalyzeLoudness'](arg1);
}

export function ApplyMetadataCandidate(arg1, arg2, arg3) {
  return window['go']['main']['App']['ApplyMetadataCandidate'](arg1, arg2, arg3);
}

export function ApplyTagEdits(arg1, arg2) {
  return window['go']['main']['App']['ApplyTagEdits'](arg1, arg2);
}

export function ApplyTagTransforms(arg1, arg2) {
  return window['go']['main']['App']['ApplyTagTransforms'](arg1, arg2);
}

export function CancelBackgroundJob(arg1) {
  return window['go']['main']['App']['CancelBackgroundJob'](arg1);
}

export function CancelScan() {
  return window['go']['main']['App']['CancelScan']();
}

export function Close() {
  return window['go']['main']['App']['Close']();
}

export function CreateEssentiaAnalysisJob(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateEssentiaAnalysisJob'](arg1, arg2, arg3, arg4);
}

export function CreateLibraryEssentiaAnalysisJob(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateLibraryEssentiaAnalysisJob'](arg1, arg2, arg3);
}

export function CreateLibraryMetadataEnrichmentJob(arg1) {
  return window['go']['main']['App']['CreateLibraryMetadataEnrichmentJob'](arg1);
}

export function CreateMetadataEnrichmentJob(arg1, arg2) {
  return window['go']['main']['App']['CreateMetadataEnrichmentJob'](arg1, arg2);
}

export function DeleteDuplicateTracks(arg1, arg2) {
  return window['go']['main']['App']['DeleteDuplicateTracks'](arg1, arg2);
}

export function DeleteSavedDJMixPlan(arg1) {
  return window['go']['main']['App']['DeleteSavedDJMixPlan'](arg1);
}

export function EnrichMetadata(arg1, arg2) {
  return window['go']['main']['App']['EnrichMetadata'](arg1, arg2);
}

export function ExportDJMixPlan(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportDJMixPlan'](arg1, arg2, arg3);
}

export function FindDuplicates() {
  return window['go']['main']['App']['FindDuplicates']();
}

export function GenerateSpectrograms(arg1, arg2) {
  return window['go']['main']['App']['GenerateSpectrograms'](arg1, arg2);
}

export function GetEssentiaPerformance() {
  return window['go']['main']['App']['GetEssentiaPerformance']();
}

export function GetMetadataSettings() {
  return window['go']['main']['App']['GetMetadataSettings']();
}

export function LibraryStatistics() {
  return window['go']['main']['App']['LibraryStatistics']();
}

export function ListBackgroundJobItems(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListBackgroundJobItems'](arg1, arg2, arg3);
}

export function ListBackgroundJobs(arg1) {
  return window['go']['main']['App']['ListBackgroundJobs'](arg1);
}

export function ListLibraryRoots() {
  return window['go']['main']['App']['ListLibraryRoots']();
}

export function ListRunningBackgroundJobItems(arg1, arg2) {
  return window['go']['main']['App']['ListRunningBackgroundJobItems'](arg1, arg2);
}

export function ListSavedDJMixPlans(arg1) {
  return window['go']['main']['App']['ListSavedDJMixPlans'](arg1);
}

export function ListTagHistory(arg1) {
  return window['go']['main']['App']['ListTagHistory'](arg1);
}

export function ListTracks(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListTracks'](arg1, arg2, arg3);
}

export function LoadSavedDJMixPlan(arg1) {
  return window['go']['main']['App']['LoadSavedDJMixPlan'](arg1);
}

export function LookupMetadata(arg1) {
  return window['go']['main']['App']['LookupMetadata'](arg1);
}

export function NormalizeTrack(arg1, arg2) {
  return window['go']['main']['App']['NormalizeTrack'](arg1, arg2);
}

export function OpenEssentiaDownloadPage() {
  return window['go']['main']['App']['OpenEssentiaDownloadPage']();
}

export function OpenMetadataLink(arg1) {
  return window['go']['main']['App']['OpenMetadataLink'](arg1);
}

export function OrganizeTrack(arg1, arg2) {
  return window['go']['main']['App']['OrganizeTrack'](arg1, arg2);
}

export function PauseBackgroundJob(arg1) {
  return window['go']['main']['App']['PauseBackgroundJob'](arg1);
}

export function PlanDJMix(arg1, arg2) {
  return window['go']['main']['App']['PlanDJMix'](arg1, arg2);
}

export function PrepareTrackAudioPreview(arg1) {
  return window['go']['main']['App']['PrepareTrackAudioPreview'](arg1);
}

export function PrepareTrackCover(arg1) {
  return window['go']['main']['App']['PrepareTrackCover'](arg1);
}

export function PrepareTrackMedia(arg1) {
  return window['go']['main']['App']['PrepareTrackMedia'](arg1);
}

export function PreviewRename(arg1, arg2) {
  return window['go']['main']['App']['PreviewRename'](arg1, arg2);
}

export function PreviewTagEdits(arg1, arg2) {
  return window['go']['main']['App']['PreviewTagEdits'](arg1, arg2);
}

export function PreviewTagTransforms(arg1, arg2) {
  return window['go']['main']['App']['PreviewTagTransforms'](arg1, arg2);
}

export function QuarantineDuplicateTracks(arg1, arg2) {
  return window['go']['main']['App']['QuarantineDuplicateTracks'](arg1, arg2);
}

export function ReadTrackTags(arg1) {
  return window['go']['main']['App']['ReadTrackTags'](arg1);
}

export function RefreshMetadata(arg1) {
  return window['go']['main']['App']['RefreshMetadata'](arg1);
}

export function RemoveCoverArt(arg1) {
  return window['go']['main']['App']['RemoveCoverArt'](arg1);
}

export function RemoveLibraryRoot(arg1, arg2) {
  return window['go']['main']['App']['RemoveLibraryRoot'](arg1, arg2);
}

export function ResetEssentiaExecutable() {
  return window['go']['main']['App']['ResetEssentiaExecutable']();
}

export function ResumeBackgroundJob(arg1) {
  return window['go']['main']['App']['ResumeBackgroundJob'](arg1);
}

export function RetryFailedBackgroundJob(arg1) {
  return window['go']['main']['App']['RetryFailedBackgroundJob'](arg1);
}

export function SaveDJMixPlan(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SaveDJMixPlan'](arg1, arg2, arg3, arg4, arg5);
}

export function SaveEssentiaPerformance(arg1) {
  return window['go']['main']['App']['SaveEssentiaPerformance'](arg1);
}

export function SaveMetadataSettings(arg1) {
  return window['go']['main']['App']['SaveMetadataSettings'](arg1);
}

export function ScanFolder(arg1) {
  return window['go']['main']['App']['ScanFolder'](arg1);
}

export function SelectCoverArt() {
  return window['go']['main']['App']['SelectCoverArt']();
}

export function SelectDuplicateQuarantineFolder() {
  return window['go']['main']['App']['SelectDuplicateQuarantineFolder']();
}

export function SelectEssentiaExecutable() {
  return window['go']['main']['App']['SelectEssentiaExecutable']();
}

export function SelectMusicFolder() {
  return window['go']['main']['App']['SelectMusicFolder']();
}

export function SetCoverArt(arg1, arg2) {
  return window['go']['main']['App']['SetCoverArt'](arg1, arg2);
}

export function SystemStatus() {
  return window['go']['main']['App']['SystemStatus']();
}

export function TestMetadataProviders(arg1) {
  return window['go']['main']['App']['TestMetadataProviders'](arg1);
}

export function UndoTagChange(arg1) {
  return window['go']['main']['App']['UndoTagChange'](arg1);
}

export function UpdateFFmpeg() {
  return window['go']['main']['App']['UpdateFFmpeg']();
}

export function VerifyDuplicateAudio(arg1) {
  return window['go']['main']['App']['VerifyDuplicateAudio'](arg1);
}

export function WriteReplayGain(arg1, arg2) {
  return window['go']['main']['App']['WriteReplayGain'](arg1, arg2);
}
