// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeBPMKey(arg1) {
  return window['go']['main']['App']['AnalyzeBPMKey'](arg1);
}

export function AnalyzeLoudness(arg1) {
  return window['go']['main']['App']['AnalyzeLoudness'](arg1);
}

export function ApplyMetadataCandidate(arg1, arg2, arg3) {
  return window['go']['main']['App']['ApplyMetadataCandidate'](arg1, arg2, arg3);
}

export function ApplyTagEdits(arg1, arg2) {
  return window['go']['main']['App']['ApplyTagEdits'](arg1, arg2);
}

export function CancelScan() {
  return window['go']['main']['App']['CancelScan']();
}

export function Close() {
  return window['go']['main']['App']['Close']();
}

export function FindDuplicates() {
  return window['go']['main']['App']['FindDuplicates']();
}

export function LibraryStatistics() {
  return window['go']['main']['App']['LibraryStatistics']();
}

export function ListLibraryRoots() {
  return window['go']['main']['App']['ListLibraryRoots']();
}

export function ListTagHistory(arg1) {
  return window['go']['main']['App']['ListTagHistory'](arg1);
}

export function ListTracks(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListTracks'](arg1, arg2, arg3);
}

export function LookupMetadata(arg1) {
  return window['go']['main']['App']['LookupMetadata'](arg1);
}

export function NormalizeTrack(arg1, arg2) {
  return window['go']['main']['App']['NormalizeTrack'](arg1, arg2);
}

export function OrganizeTrack(arg1, arg2) {
  return window['go']['main']['App']['OrganizeTrack'](arg1, arg2);
}

export function PreviewRename(arg1, arg2) {
  return window['go']['main']['App']['PreviewRename'](arg1, arg2);
}

export function PreviewTagEdits(arg1, arg2) {
  return window['go']['main']['App']['PreviewTagEdits'](arg1, arg2);
}

export function ReadTrackTags(arg1) {
  return window['go']['main']['App']['ReadTrackTags'](arg1);
}

export function RemoveCoverArt(arg1) {
  return window['go']['main']['App']['RemoveCoverArt'](arg1);
}

export function RemoveLibraryRoot(arg1, arg2) {
  return window['go']['main']['App']['RemoveLibraryRoot'](arg1, arg2);
}

export function ScanFolder(arg1) {
  return window['go']['main']['App']['ScanFolder'](arg1);
}

export function SelectCoverArt() {
  return window['go']['main']['App']['SelectCoverArt']();
}

export function SelectMusicFolder() {
  return window['go']['main']['App']['SelectMusicFolder']();
}

export function SetCoverArt(arg1, arg2) {
  return window['go']['main']['App']['SetCoverArt'](arg1, arg2);
}

export function SystemStatus() {
  return window['go']['main']['App']['SystemStatus']();
}

export function UndoTagChange(arg1) {
  return window['go']['main']['App']['UndoTagChange'](arg1);
}

export function UpdateFFmpeg() {
  return window['go']['main']['App']['UpdateFFmpeg']();
}

export function WriteReplayGain(arg1, arg2) {
  return window['go']['main']['App']['WriteReplayGain'](arg1, arg2);
}
