// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function AnalyzeBPMKey(arg1:number):Promise<model.BPMKey>;

export function AnalyzeLoudness(arg1:number):Promise<model.Loudness>;

export function ApplyMetadataCandidate(arg1:number,arg2:model.MetadataCandidate,arg3:boolean):Promise<model.TagApplyResult>;

export function ApplyTagEdits(arg1:Array<number>,arg2:model.TagPatch):Promise<model.TagApplyResult>;

export function ApplyTagTransforms(arg1:Array<number>,arg2:model.TagTransformRequest):Promise<model.TagApplyResult>;

export function CancelBackgroundJob(arg1:number):Promise<model.BackgroundJob>;

export function CancelScan():Promise<boolean>;

export function Close():Promise<void>;

export function CreateLibraryMetadataEnrichmentJob(arg1:model.MetadataEnrichmentOptions):Promise<model.BackgroundJob>;

export function CreateMetadataEnrichmentJob(arg1:Array<number>,arg2:model.MetadataEnrichmentOptions):Promise<model.BackgroundJob>;

export function DeleteDuplicateTracks(arg1:Array<number>,arg2:string):Promise<model.DuplicateActionResult>;

export function EnrichMetadata(arg1:Array<number>,arg2:model.MetadataEnrichmentOptions):Promise<model.MetadataEnrichmentResult>;

export function FindDuplicates():Promise<Array<model.DuplicateGroup>>;

export function GenerateSpectrograms(arg1:number,arg2:string):Promise<model.SpectrogramComparison>;

export function GetMetadataSettings():Promise<model.MetadataSettings>;

export function LibraryStatistics():Promise<model.LibraryStats>;

export function ListBackgroundJobItems(arg1:number,arg2:number,arg3:number):Promise<Array<model.BackgroundJobItem>>;

export function ListBackgroundJobs(arg1:number):Promise<Array<model.BackgroundJob>>;

export function ListLibraryRoots():Promise<Array<model.LibraryRoot>>;

export function ListRunningBackgroundJobItems(arg1:number,arg2:number):Promise<Array<model.BackgroundJobItem>>;

export function ListTagHistory(arg1:number):Promise<Array<model.TagHistory>>;

export function ListTracks(arg1:string,arg2:number,arg3:number):Promise<Array<model.Track>>;

export function LookupMetadata(arg1:number):Promise<model.MetadataLookupResult>;

export function NormalizeTrack(arg1:number,arg2:model.ProcessingOptions):Promise<model.ProcessingResult>;

export function OpenEssentiaDownloadPage():Promise<void>;

export function OpenMetadataLink(arg1:string):Promise<void>;

export function OrganizeTrack(arg1:number,arg2:model.OrganizeRequest):Promise<string>;

export function PauseBackgroundJob(arg1:number):Promise<model.BackgroundJob>;

export function PrepareTrackAudioPreview(arg1:number):Promise<string>;

export function PrepareTrackCover(arg1:number):Promise<string>;

export function PrepareTrackMedia(arg1:number):Promise<model.TrackMedia>;

export function PreviewRename(arg1:number,arg2:model.OrganizeRequest):Promise<string>;

export function PreviewTagEdits(arg1:Array<number>,arg2:model.TagPatch):Promise<Array<model.TagPreview>>;

export function PreviewTagTransforms(arg1:Array<number>,arg2:model.TagTransformRequest):Promise<Array<model.TagPreview>>;

export function QuarantineDuplicateTracks(arg1:Array<number>,arg2:string):Promise<model.DuplicateActionResult>;

export function ReadTrackTags(arg1:number):Promise<model.TagSnapshot>;

export function RefreshMetadata(arg1:number):Promise<model.MetadataLookupResult>;

export function RemoveCoverArt(arg1:Array<number>):Promise<model.TagApplyResult>;

export function RemoveLibraryRoot(arg1:string,arg2:boolean):Promise<void>;

export function ResetEssentiaExecutable():Promise<model.SystemStatus>;

export function ResumeBackgroundJob(arg1:number):Promise<model.BackgroundJob>;

export function RetryFailedBackgroundJob(arg1:number):Promise<model.BackgroundJob>;

export function SaveMetadataSettings(arg1:model.MetadataSettings):Promise<model.MetadataSettings>;

export function ScanFolder(arg1:string):Promise<model.ScanResult>;

export function SelectCoverArt():Promise<string>;

export function SelectDuplicateQuarantineFolder():Promise<string>;

export function SelectEssentiaExecutable():Promise<model.SystemStatus>;

export function SelectMusicFolder():Promise<string>;

export function SetCoverArt(arg1:Array<number>,arg2:string):Promise<model.TagApplyResult>;

export function SystemStatus():Promise<model.SystemStatus>;

export function TestMetadataProviders(arg1:model.MetadataSettings):Promise<Array<model.MetadataProviderReport>>;

export function UndoTagChange(arg1:number):Promise<model.TagApplyResult>;

export function UpdateFFmpeg():Promise<model.FFmpegUpdateResult>;

export function VerifyDuplicateAudio(arg1:Array<number>):Promise<model.DuplicateAudioVerification>;

export function WriteReplayGain(arg1:number,arg2:number):Promise<model.Loudness>;
